import { MigrationInterface, QueryRunner } from "typeorm";

export class AddRestaurantPaymentMethods1777819143121 implements MigrationInterface {
    name = 'AddRestaurantPaymentMethods1777819143121'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "restaurants" DROP CONSTRAINT "FK_restaurants_owner"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_products_restaurant"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_payments_order"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_payments_payment_method"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_orders_customer"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_orders_restaurant"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_order_items_order"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_order_items_product"`);
        await queryRunner.query(`ALTER TABLE "drivers" DROP CONSTRAINT "FK_drivers_user"`);
        await queryRunner.query(`ALTER TABLE "deliveries" DROP CONSTRAINT "FK_deliveries_order"`);
        await queryRunner.query(`ALTER TABLE "deliveries" DROP CONSTRAINT "FK_deliveries_driver"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_users_email"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_restaurants_name"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_products_restaurantId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_payments_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_orders_customerId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_orders_restaurantId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_orders_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_order_items_orderId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_drivers_isAvailable"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_deliveries_driverId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_deliveries_status"`);
        await queryRunner.query(`CREATE TABLE "restaurant_reviews" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "restaurantId" uuid NOT NULL, "customerId" uuid NOT NULL, "orderId" uuid NOT NULL, "rating" smallint NOT NULL, "comment" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_review_customer_order" UNIQUE ("customerId", "orderId"), CONSTRAINT "PK_b8103daf77b1e7dfd2cfa3ba73a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3e6d0f5a8ec4fdc5a8c0cd5198" ON "restaurant_reviews" ("restaurantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_59fcdd4727e81af5ebea3740cb" ON "restaurant_reviews" ("customerId") `);
        await queryRunner.query(`CREATE TABLE "restaurant_payment_methods" ("restaurantId" uuid NOT NULL, "paymentMethodId" uuid NOT NULL, CONSTRAINT "PK_bef994730104998b0b426212d0c" PRIMARY KEY ("restaurantId", "paymentMethodId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_36a6e35c8166fe0815a462fa39" ON "restaurant_payment_methods" ("restaurantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_365f3895df864e0385f7397ce1" ON "restaurant_payment_methods" ("paymentMethodId") `);
        await queryRunner.query(`ALTER TABLE "restaurants" ADD "isFeatured" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "restaurants" ADD "estimatedDeliveryMinutes" integer NOT NULL DEFAULT '30'`);
        await queryRunner.query(`ALTER TABLE "restaurants" ADD "averageRating" numeric(3,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "restaurants" ADD "totalReviews" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "restaurants" ADD "totalOrders" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "restaurants" ADD "logoUrl" character varying`);
        await queryRunner.query(`ALTER TABLE "restaurants" ADD "bannerUrl" character varying`);
        await queryRunner.query(`ALTER TABLE "drivers" ALTER COLUMN "rating" SET DEFAULT '5'`);
        await queryRunner.query(`CREATE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users" ("email") `);
        await queryRunner.query(`CREATE INDEX "IDX_dfeffbef9c31936dbac54733da" ON "restaurants" ("name") `);
        await queryRunner.query(`CREATE INDEX "IDX_11a1d3b4f6f1c6630be3127391" ON "products" ("restaurantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_32b41cdb985a296213e9a928b5" ON "payments" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_e5de51ca888d8b1f5ac25799dd" ON "orders" ("customerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_2312cd07a04f50ba29d76c9564" ON "orders" ("restaurantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_775c9f06fc27ae3ff8fb26f2c4" ON "orders" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_f1d359a55923bb45b057fbdab0" ON "order_items" ("orderId") `);
        await queryRunner.query(`CREATE INDEX "IDX_57b90ac509ac4b5f68267aaae7" ON "drivers" ("isAvailable") `);
        await queryRunner.query(`CREATE INDEX "IDX_a6cc84e1c957ed2d25bd7eda4b" ON "deliveries" ("driverId") `);
        await queryRunner.query(`CREATE INDEX "IDX_3235c9c06d9d3028a11ec8081d" ON "deliveries" ("status") `);
        await queryRunner.query(`ALTER TABLE "restaurants" ADD CONSTRAINT "FK_9519e81d388514ec631d23fefca" FOREIGN KEY ("ownerId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_11a1d3b4f6f1c6630be3127391d" FOREIGN KEY ("restaurantId") REFERENCES "restaurants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "restaurant_reviews" ADD CONSTRAINT "FK_3e6d0f5a8ec4fdc5a8c0cd51989" FOREIGN KEY ("restaurantId") REFERENCES "restaurants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "restaurant_reviews" ADD CONSTRAINT "FK_59fcdd4727e81af5ebea3740cb2" FOREIGN KEY ("customerId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "restaurant_reviews" ADD CONSTRAINT "FK_cbe432ac8e60063f2b9437d3b34" FOREIGN KEY ("orderId") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_af929a5f2a400fdb6913b4967e1" FOREIGN KEY ("orderId") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_cbe18cae039006a9c217d5a66a6" FOREIGN KEY ("paymentMethodId") REFERENCES "payment_methods"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_e5de51ca888d8b1f5ac25799dd1" FOREIGN KEY ("customerId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_2312cd07a04f50ba29d76c9564e" FOREIGN KEY ("restaurantId") REFERENCES "restaurants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_f1d359a55923bb45b057fbdab0d" FOREIGN KEY ("orderId") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_cdb99c05982d5191ac8465ac010" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "drivers" ADD CONSTRAINT "FK_57d866371f392f459cd9ee46f6a" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "deliveries" ADD CONSTRAINT "FK_f7433e3639e213f901e22cf8640" FOREIGN KEY ("orderId") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "deliveries" ADD CONSTRAINT "FK_a6cc84e1c957ed2d25bd7eda4ba" FOREIGN KEY ("driverId") REFERENCES "drivers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "restaurant_payment_methods" ADD CONSTRAINT "FK_36a6e35c8166fe0815a462fa395" FOREIGN KEY ("restaurantId") REFERENCES "restaurants"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "restaurant_payment_methods" ADD CONSTRAINT "FK_365f3895df864e0385f7397ce1a" FOREIGN KEY ("paymentMethodId") REFERENCES "payment_methods"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "restaurant_payment_methods" DROP CONSTRAINT "FK_365f3895df864e0385f7397ce1a"`);
        await queryRunner.query(`ALTER TABLE "restaurant_payment_methods" DROP CONSTRAINT "FK_36a6e35c8166fe0815a462fa395"`);
        await queryRunner.query(`ALTER TABLE "deliveries" DROP CONSTRAINT "FK_a6cc84e1c957ed2d25bd7eda4ba"`);
        await queryRunner.query(`ALTER TABLE "deliveries" DROP CONSTRAINT "FK_f7433e3639e213f901e22cf8640"`);
        await queryRunner.query(`ALTER TABLE "drivers" DROP CONSTRAINT "FK_57d866371f392f459cd9ee46f6a"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_cdb99c05982d5191ac8465ac010"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_f1d359a55923bb45b057fbdab0d"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_2312cd07a04f50ba29d76c9564e"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_e5de51ca888d8b1f5ac25799dd1"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_cbe18cae039006a9c217d5a66a6"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_af929a5f2a400fdb6913b4967e1"`);
        await queryRunner.query(`ALTER TABLE "restaurant_reviews" DROP CONSTRAINT "FK_cbe432ac8e60063f2b9437d3b34"`);
        await queryRunner.query(`ALTER TABLE "restaurant_reviews" DROP CONSTRAINT "FK_59fcdd4727e81af5ebea3740cb2"`);
        await queryRunner.query(`ALTER TABLE "restaurant_reviews" DROP CONSTRAINT "FK_3e6d0f5a8ec4fdc5a8c0cd51989"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_11a1d3b4f6f1c6630be3127391d"`);
        await queryRunner.query(`ALTER TABLE "restaurants" DROP CONSTRAINT "FK_9519e81d388514ec631d23fefca"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3235c9c06d9d3028a11ec8081d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a6cc84e1c957ed2d25bd7eda4b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_57b90ac509ac4b5f68267aaae7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f1d359a55923bb45b057fbdab0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_775c9f06fc27ae3ff8fb26f2c4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2312cd07a04f50ba29d76c9564"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e5de51ca888d8b1f5ac25799dd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_32b41cdb985a296213e9a928b5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_11a1d3b4f6f1c6630be3127391"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dfeffbef9c31936dbac54733da"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97672ac88f789774dd47f7c8be"`);
        await queryRunner.query(`ALTER TABLE "drivers" ALTER COLUMN "rating" SET DEFAULT 5.0`);
        await queryRunner.query(`ALTER TABLE "restaurants" DROP COLUMN "bannerUrl"`);
        await queryRunner.query(`ALTER TABLE "restaurants" DROP COLUMN "logoUrl"`);
        await queryRunner.query(`ALTER TABLE "restaurants" DROP COLUMN "totalOrders"`);
        await queryRunner.query(`ALTER TABLE "restaurants" DROP COLUMN "totalReviews"`);
        await queryRunner.query(`ALTER TABLE "restaurants" DROP COLUMN "averageRating"`);
        await queryRunner.query(`ALTER TABLE "restaurants" DROP COLUMN "estimatedDeliveryMinutes"`);
        await queryRunner.query(`ALTER TABLE "restaurants" DROP COLUMN "isFeatured"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_365f3895df864e0385f7397ce1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_36a6e35c8166fe0815a462fa39"`);
        await queryRunner.query(`DROP TABLE "restaurant_payment_methods"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_59fcdd4727e81af5ebea3740cb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3e6d0f5a8ec4fdc5a8c0cd5198"`);
        await queryRunner.query(`DROP TABLE "restaurant_reviews"`);
        await queryRunner.query(`CREATE INDEX "IDX_deliveries_status" ON "deliveries" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_deliveries_driverId" ON "deliveries" ("driverId") `);
        await queryRunner.query(`CREATE INDEX "IDX_drivers_isAvailable" ON "drivers" ("isAvailable") `);
        await queryRunner.query(`CREATE INDEX "IDX_order_items_orderId" ON "order_items" ("orderId") `);
        await queryRunner.query(`CREATE INDEX "IDX_orders_status" ON "orders" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_orders_restaurantId" ON "orders" ("restaurantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_orders_customerId" ON "orders" ("customerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_payments_status" ON "payments" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_products_restaurantId" ON "products" ("restaurantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_restaurants_name" ON "restaurants" ("name") `);
        await queryRunner.query(`CREATE INDEX "IDX_users_email" ON "users" ("email") `);
        await queryRunner.query(`ALTER TABLE "deliveries" ADD CONSTRAINT "FK_deliveries_driver" FOREIGN KEY ("driverId") REFERENCES "drivers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "deliveries" ADD CONSTRAINT "FK_deliveries_order" FOREIGN KEY ("orderId") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "drivers" ADD CONSTRAINT "FK_drivers_user" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_order_items_product" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_order_items_order" FOREIGN KEY ("orderId") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_orders_restaurant" FOREIGN KEY ("restaurantId") REFERENCES "restaurants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_orders_customer" FOREIGN KEY ("customerId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_payments_payment_method" FOREIGN KEY ("paymentMethodId") REFERENCES "payment_methods"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_payments_order" FOREIGN KEY ("orderId") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_products_restaurant" FOREIGN KEY ("restaurantId") REFERENCES "restaurants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "restaurants" ADD CONSTRAINT "FK_restaurants_owner" FOREIGN KEY ("ownerId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
